// Code generated by go run ../internal/gen -cp 932; DO NOT EDIT.

package cp932

import "github.com/doxuta/bestfit"

// JIS holds the SHIFTJIS.TXT rows (the JIS X 0208 mapping used by Apple, glibc and iconv)
// whose bytes CP932.TXT (Microsoft) assigns to a different code point. The WHATWG
// Shift_JIS encoder's three special cases (¥→0x5C, ‾→0x7E, −→－) are among them.
// 8 rows.
var JIS = bestfit.Table{
	0x00A2: "￠",  // ¢
	0x00A3: "￡",  // £
	0x00A5: "\\", // ¥
	0x00AC: "￢",  // ¬
	0x2016: "∥",  // ‖
	0x203E: "~",  // ‾
	0x2212: "－",  // −
	0x301C: "～",  // 〜
}

// Windows holds the bestfit932.txt WCTABLE rows that do not round-trip: what
// WideCharToMultiByte writes when WC_NO_BEST_FIT_CHARS is not set. Only rows the
// base encoding refuses are kept.
// 84 rows.
var Windows = bestfit.Table{
	0x00A1: "!",  // ¡
	0x00A2: "￠",  // ¢
	0x00A3: "￡",  // £
	0x00A5: "\\", // ¥
	0x00A6: "|",  // ¦
	0x00A9: "c",  // ©
	0x00AA: "a",  // ª
	0x00AB: "≪",  // «
	0x00AC: "￢",  // ¬
	0x00AD: "-",
	0x00AE: "R", // ®
	0x00AF: "￣", // ¯
	0x00B2: "2", // ²
	0x00B3: "3", // ³
	0x00B5: "μ", // µ
	0x00B7: "・", // ·
	0x00B8: "，", // ¸
	0x00B9: "1", // ¹
	0x00BA: "o", // º
	0x00BB: "≫", // »
	0x00BF: "?", // ¿
	0x00C0: "A", // À
	0x00C1: "A", // Á
	0x00C2: "A", // Â
	0x00C3: "A", // Ã
	0x00C4: "A", // Ä
	0x00C5: "A", // Å
	0x00C6: "A", // Æ
	0x00C7: "C", // Ç
	0x00C8: "E", // È
	0x00C9: "E", // É
	0x00CA: "E", // Ê
	0x00CB: "E", // Ë
	0x00CC: "I", // Ì
	0x00CD: "I", // Í
	0x00CE: "I", // Î
	0x00CF: "I", // Ï
	0x00D0: "D", // Ð
	0x00D1: "N", // Ñ
	0x00D2: "O", // Ò
	0x00D3: "O", // Ó
	0x00D4: "O", // Ô
	0x00D5: "O", // Õ
	0x00D6: "O", // Ö
	0x00D8: "O", // Ø
	0x00D9: "U", // Ù
	0x00DA: "U", // Ú
	0x00DB: "U", // Û
	0x00DC: "U", // Ü
	0x00DD: "Y", // Ý
	0x00DE: "T", // Þ
	0x00DF: "s", // ß
	0x00E0: "a", // à
	0x00E1: "a", // á
	0x00E2: "a", // â
	0x00E3: "a", // ã
	0x00E4: "a", // ä
	0x00E5: "a", // å
	0x00E6: "a", // æ
	0x00E7: "c", // ç
	0x00E8: "e", // è
	0x00E9: "e", // é
	0x00EA: "e", // ê
	0x00EB: "e", // ë
	0x00EC: "i", // ì
	0x00ED: "i", // í
	0x00EE: "i", // î
	0x00EF: "i", // ï
	0x00F0: "d", // ð
	0x00F1: "n", // ñ
	0x00F2: "o", // ò
	0x00F3: "o", // ó
	0x00F4: "o", // ô
	0x00F5: "o", // õ
	0x00F6: "o", // ö
	0x00F8: "o", // ø
	0x00F9: "u", // ù
	0x00FA: "u", // ú
	0x00FB: "u", // û
	0x00FC: "u", // ü
	0x00FD: "y", // ý
	0x00FE: "t", // þ
	0x00FF: "y", // ÿ
	0x3094: "ヴ", // ゔ
}
